minimum_pre_commit_version: '4.4.0'

repos:
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy --fix
        entry: clang-tidy -p=out/build/quality --fix
        language: unsupported
        files: ^(src|tests|examples)/.*\.cpp$
        require_serial: true

      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: unsupported
        files: \.(cpp|hpp|cu)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
