"""Runnable checks for regeneration and failure atomicity; standard library only."""

import json
import tempfile
from copy import deepcopy
from pathlib import Path
from unittest.mock import patch

import american
import asian
import barrier
import binary
import digital
import generate
import oracle as g


def check_generation():
    barrier.check_bindings()
    binary.check_bindings()
    asian.check_bindings()
    original = generate.FIXTURE.read_bytes()
    scenarios = generate.load_scenarios(g.PROJECT / "scenarios.json")
    profiles = generate.numerical_profiles(g.PROJECT / "numerical_engines.json")
    with tempfile.TemporaryDirectory() as directory:
        fixture = Path(directory) / "fixture.tsv"
        inputs = Path(directory) / "scenarios.json"
        engines = Path(directory) / "engines.json"
        fixture.write_text("unsupported-reference\n")

        def write_scenarios(cases):
            inputs.write_text(
                json.dumps(
                    {
                        "defaults": {
                            field: {}
                            for field in (
                                "inputs",
                                "tolerances",
                                "numerical_tolerances",
                            )
                        },
                        "scenarios": cases,
                    }
                )
            )

        inputs.write_bytes((g.PROJECT / "scenarios.json").read_bytes())
        with patch.object(g, "reference", wraps=g.reference) as references:
            generate.regenerate(fixture, inputs)
            contracts = [
                tuple(sorted(call.args[0].items()))
                for call in references.call_args_list
            ]
            assert len(contracts) == len(set(contracts)), (
                "reference recomputed for another engine"
            )
        first = fixture.read_bytes()
        generate.regenerate(fixture, inputs)
        assert fixture.read_bytes() == first == original, (
            "regeneration must match committed bytes"
        )
        rows = [
            line.split("\t")
            for line in first.decode().splitlines()
            if line and not line.startswith("#")
        ]
        assert rows.pop(0) == g.HEADER
        assert len(rows) == 664
        assert all(
            row[0].startswith("ql-") and g.attributes(row[4]).get("owner") == "QuantLib"
            for row in rows
        ), "all references must be generated by QuantLib"
        asian_rows = [row for row in rows if row[1] in asian.INSTRUMENTS.values()]
        assert len(asian_rows) == 24
        assert sum(g.attributes(row[4])["wrapper"] == "true" for row in asian_rows) == 6
        for row in asian_rows:
            terms = g.attributes(row[4])
            assert terms["source_symbol"] == (
                "QuantLib.PlainVanillaPayoff"
                if terms["valuation"] == terms["expiry_date"]
                else asian.SOURCES[terms["averaging"]]
            )
            assert (terms["reference_kind"] == "approximate") == (
                terms["averaging"] == "arithmetic"
                and terms["valuation"] != terms["expiry_date"]
            )
        binary_rows = [
            row for row in rows if row[1] in {"BinaryBarrierOption", "TouchOption"}
        ]
        assert len(binary_rows) == 268
        assert sum(row[1] == "BinaryBarrierOption" for row in binary_rows) == 160
        assert sum(row[1] == "TouchOption" for row in binary_rows) == 108
        assert (
            sum(g.attributes(row[4])["wrapper"] == "true" for row in binary_rows) == 140
        )
        assert sum(len(g.attributes(row[5])) == 1 for row in binary_rows) == 100
        barrier_rows = [row for row in rows if row[1] == "BarrierOption"]
        assert len(barrier_rows) == 120
        for engine in barrier.ENGINES:
            matching = [row for row in barrier_rows if row[2] == engine]
            assert len(matching) == 60
            assert sum(
                g.attributes(row[4])["wrapper"] == "true" for row in matching
            ) == (48 if engine == barrier.ENGINES[0] else 12)
        digital_rows = [row for row in rows if row[1] in digital.INSTRUMENTS.values()]
        assert len(digital_rows) == 120, "digital matrix incomplete"
        for engine in digital.ENGINES:
            matching = [row for row in digital_rows if row[2] == engine]
            assert len(matching) == 40
            assert sum(
                g.attributes(row[4])["wrapper"] == "true" for row in matching
            ) == (4 if engine == "FiniteDifferenceDigitalEngine" else 36)
        for profile in profiles:
            matching = [
                row
                for row in rows
                if row[1] == "EuropeanOption" and row[2] == profile["engine"]
            ]
            assert len(matching) == 18, "numerical matrix incomplete"
            assert (
                sum(g.attributes(row[4])["wrapper"] == "true" for row in matching) == 2
            )
        american_rows = [row for row in rows if row[1] == "AmericanOption"]
        american_inputs = {
            case["case_id"]: case["inputs"]
            for case in json.loads((g.PROJECT / "american.json").read_text())[
                "scenarios"
            ]
        }
        assert len(american_rows) == 40, "American matrix incomplete"
        for engine in american.ENGINES:
            matching = [row for row in american_rows if row[2] == engine]
            assert len(matching) == 10
            assert (
                sum(g.attributes(row[4])["wrapper"] == "true" for row in matching) == 2
            )
        for row in american_rows:
            attributes = g.attributes(row[4])
            assert attributes["source_symbol"] == "QuantLib.FdBlackScholesVanillaEngine"
            assert float(attributes["refinement_price"]) <= american.STABILITY["price"]
            if float(attributes["refinement_price"]) > max(
                1e-9, float(attributes["coarse_refinement_price"])
            ):
                # Grid alignment can make tiny discretization errors non-monotonic.
                # Verify another refinement against the existing uncertainty, without enlarging it.
                market = american_inputs[row[0].rsplit("-", 1)[0]]
                refined = american.measure(market, "price", (6400, 6400))
                price = float(g.attributes(row[5])["price"])
                assert abs(refined - price) <= float(attributes["uncertainty_price"])
        lines = first.decode().splitlines()
        index = next(i for i, line in enumerate(lines) if line.startswith("ql-"))
        fields = lines[index].split("\t")
        outputs = g.attributes(fields[5])
        outputs["price"] = 123456.0
        fields[5] = g.encode(outputs)
        lines[index] = "\t".join(fields)
        fixture.write_text("\n".join(lines) + "\n")
        generate.regenerate(fixture, inputs)
        assert fixture.read_bytes() == first, "owned prices must be recomputed"

        invalid = []
        for key in g.INPUTS:
            case = deepcopy(scenarios)
            del case[0]["inputs"][key]
            invalid.append(case)
        invalid.append(scenarios + [scenarios[0]])
        for value in (-1, float("nan"), float("inf")):
            case = deepcopy(scenarios)
            case[0]["tolerances"]["price"] = value
            invalid.append(case)
        for field, value in (
            ("option", "unknown"),
            ("spot", 0),
            ("rate", float("nan")),
            ("expiry_date", "2025-01-06"),
        ):
            case = deepcopy(scenarios)
            case[0]["inputs"][field] = value
            invalid.append(case)
        for case in invalid:
            write_scenarios(case)
            try:
                generate.regenerate(fixture, inputs)
            except ValueError:
                pass
            else:
                raise AssertionError("invalid scenario accepted")
            assert fixture.read_bytes() == first, "failure replaced fixture"

        write_scenarios(scenarios)
        invalid_profiles = []
        for mutation in (
            "unknown engine",
            "unknown setting",
            "fractional steps",
            "bad shift",
            "missing budget",
        ):
            changed = deepcopy(profiles)
            if mutation == "unknown engine":
                changed[0]["engine"] = "UnknownEngine"
            elif mutation == "unknown setting":
                changed[0]["settings"]["typo"] = 1
            elif mutation == "fractional steps":
                changed[0]["settings"]["steps"] = 1.5
            elif mutation == "bad shift":
                changed[0]["shifts"]["spot_shift"] = float("nan")
            else:
                del changed[0]["numerical_tolerances"]["zomma"]
            invalid_profiles.append(changed)
        for changed in invalid_profiles:
            engines.write_text(
                json.dumps(
                    {
                        "profiles": changed,
                        "profile_defaults": {
                            field: {}
                            for field in (
                                "shifts",
                                "tolerances",
                                "numerical_tolerances",
                            )
                        },
                    }
                )
            )
            try:
                generate.regenerate(fixture, inputs, engines)
            except ValueError:
                pass
            else:
                raise AssertionError("invalid numerical profile accepted")
            assert fixture.read_bytes() == first, "invalid profile replaced fixture"
        for invalid_output in ("price=nan", "delta=1"):
            fields[5] = invalid_output
            with patch.object(g, "serialize_row", return_value="\t".join(fields)):
                try:
                    generate.regenerate(fixture, inputs)
                except ValueError:
                    pass
                else:
                    raise AssertionError("invalid output accepted")
            assert fixture.read_bytes() == first, "invalid output replaced fixture"
        real_measure = g.measure
        for bad in (float("nan"), float("inf"), 1000.0):

            def corrupted(market, name, scale=1, price_only=False, bad=bad, **options):
                if name == "vega" and scale == 2:
                    return bad
                return real_measure(market, name, scale, price_only, **options)

            with patch.object(g, "measure", side_effect=corrupted):
                try:
                    generate.regenerate(fixture, inputs)
                except ValueError:
                    pass
                else:
                    raise AssertionError("unstable or non-finite Greek accepted")
            assert fixture.read_bytes() == first, "bad Greek replaced fixture"

        real_american_measure = american.measure
        for bad in (float("nan"), float("inf"), 1000.0):

            def corrupted_american(
                market, name, grid=american.GRIDS[-1], scale=1, bad=bad
            ):
                if name == "vega" and scale == 2:
                    return bad
                return real_american_measure(market, name, grid, scale)

            with patch.object(american, "measure", side_effect=corrupted_american):
                try:
                    generate.regenerate(fixture, inputs)
                except ValueError:
                    pass
                else:
                    raise AssertionError("unstable American Greek accepted")
            assert fixture.read_bytes() == first, "bad American Greek replaced fixture"

        for field in ("payoff", "asset_settlement", "averaging"):
            for bad in (float("nan"), float("inf"), 1000.0):

                def corrupted_contract(
                    market,
                    name,
                    scale=1,
                    price_only=False,
                    field=field,
                    bad=bad,
                    **options,
                ):
                    if field in market and name == "vega" and scale == 2:
                        return bad
                    return real_measure(market, name, scale, price_only, **options)

                with patch.object(g, "measure", side_effect=corrupted_contract):
                    try:
                        generate.regenerate(fixture, inputs)
                    except ValueError:
                        pass
                    else:
                        raise AssertionError(f"unstable {field} Greek accepted")
                assert fixture.read_bytes() == first, (
                    f"bad {field} Greek replaced fixture"
                )

    # Exercise price-derived higher Greeks on the smooth matrix, independent of Kiyosi.
    for case in scenarios[:18]:
        for name in ("speed", "charm", "color", "vanna", "zomma"):
            direct = g.measure(case["inputs"], name)
            fallback = g.measure(case["inputs"], name, price_only=True)
            assert abs(direct - fallback) < 1e-7, (
                case["case_id"],
                name,
                direct,
                fallback,
            )
    for identifier, market in digital.scenarios(digital.configuration()):
        if market["expiry_date"] == "2025-01-07":
            continue
        for name in ("speed", "charm", "color", "vanna", "zomma"):
            direct = g.measure(market, name)
            fallback = g.measure(market, name, price_only=True)
            assert abs(direct - fallback) < digital.STABILITY[name], (
                identifier,
                name,
                direct,
                fallback,
            )
    # AnalyticEuropeanEngine prices pre-expiry_date; at expiry_date QuantLib marks the instrument
    # expired, so verify strict strike settlement directly through its payoff bindings.
    for direction, cash, asset in (
        (g.ql.Option.Call, [0, 0, 10], [0, 0, 101]),
        (g.ql.Option.Put, [10, 0, 0], [99, 0, 0]),
    ):
        assert [
            g.ql.CashOrNothingPayoff(direction, 100, 10)(s) for s in (99, 100, 101)
        ] == cash
        assert [
            g.ql.AssetOrNothingPayoff(direction, 100)(s) for s in (99, 100, 101)
        ] == asset
    print("Generation checks passed")


if __name__ == "__main__":
    check_generation()
