"""Generate the shared reference manifest; never consume Kiyosi prices."""

import json
import math
import os
import re
import tempfile
from importlib.metadata import version
from pathlib import Path

import american
import asian
import barrier
import binary
import digital
import oracle as g

FIXTURE = g.PROJECT.parents[1] / "tests/fixtures/pricing_reference.tsv"
NUMERICAL_ENGINES = {
    "CrrEngine": {"steps"},
    "IntegralEuropeanEngine": set(),
    "FiniteDifferenceEuropeanEngine": {
        "asset_step_count",
        "time_step_count",
        "scheme",
        "asset_upper_boundary",
    },
    "MonteCarloEuropeanEngine": {"seed", "paths", "steps"},
}


def validate_scenario(scenario):
    g.require(
        set(scenario) == {"case_id", "inputs", "tolerances", "numerical_tolerances"},
        "incomplete scenario",
    )
    g.require(
        re.fullmatch(r"ql-european-[a-z0-9-]+", scenario["case_id"]),
        "invalid case identifier",
    )
    g.validate_inputs(scenario["inputs"])
    g.validate_budgets(scenario)


def numerical_profiles(path):
    config = json.loads(path.read_text(encoding="utf-8"))
    g.require(set(config) == {"profiles", "profile_defaults"}, "invalid profiles")
    profiles = g.expand_profiles(config)
    g.require(
        isinstance(profiles, list) and len(profiles) == len(NUMERICAL_ENGINES),
        "incomplete engine profiles",
    )
    g.require(
        {p["engine"] for p in profiles} == set(NUMERICAL_ENGINES),
        "unknown or duplicate engine",
    )
    for profile in profiles:
        g.require(
            set(profile)
            == {"engine", "settings", "shifts", "tolerances", "numerical_tolerances"},
            "invalid profile",
        )
        g.validate_settings(profile["settings"], NUMERICAL_ENGINES[profile["engine"]])
        g.validate_shifts(profile["shifts"])
        g.require(profile["shifts"]["time_shift_days"] <= 3, "invalid time shift")
        g.validate_budgets(profile)
    return profiles


def numerical_row(scenario, profile, reference):
    row = g.reference_row(
        scenario["case_id"],
        scenario["inputs"],
        reference,
        profile["tolerances"],
        profile["numerical_tolerances"],
    )
    row["case_id"] += "-" + profile["engine"].lower()
    row["engine"] = profile["engine"]
    inputs = row["inputs"]
    inputs.update(profile["settings"])
    inputs.update(profile["shifts"])
    inputs["wrapper"] = str(
        scenario["inputs"]["spot"] == 100
        and scenario["inputs"]["expiry_date"] == "2026-01-06"
    ).lower()
    inputs["tolerance_rationale"] = (
        "engine-specific discretization or sampling budget, see GENERATION.md"
    )
    if row["engine"] == "MonteCarloEuropeanEngine":
        row["monte_carlo"] = "|".join(
            format(inputs[key], ".17g")
            if isinstance(inputs[key], float)
            else str(inputs[key])
            for key in ("seed", "paths", "steps", "tolerance")
        )
    return g.serialize_row(row)


def validate_manifest(text):
    seen = set()
    lines = [line for line in text.splitlines() if line and not line.startswith("#")]
    g.require(lines and lines[0].split("\t") == g.HEADER, "invalid TSV header")
    for line in lines[1:]:
        fields = line.split("\t")
        g.require(len(fields) == len(g.HEADER) and all(fields), "invalid TSV row")
        g.require(fields[0] not in seen, "duplicate case identifier")
        seen.add(fields[0])
        inputs, outputs, tolerances = map(g.attributes, fields[4:7])
        g.require(set(outputs) == set(tolerances), "outputs and tolerances must match")
        g.require(
            all(math.isfinite(float(value)) for value in outputs.values()),
            "non-finite output",
        )
        g.require(
            all(
                math.isfinite(float(value)) and float(value) >= 0
                for value in tolerances.values()
            ),
            "invalid output tolerance",
        )
        for key in (
            "source_revision",
            "source_symbol",
            "convention",
            "reference_kind",
            "tolerance",
        ):
            g.require(key in inputs, f"missing provenance {key}")
        g.require(
            math.isfinite(float(inputs["tolerance"]))
            and float(inputs["tolerance"]) >= 0,
            "invalid provenance tolerance",
        )
        g.require(
            inputs.get("owner") == "QuantLib" and fields[0].startswith("ql-"),
            "all reference rows must be generated by QuantLib",
        )

        contracts = {
            "EuropeanOption": (g.STABILITY, g.exclusions),
            "AmericanOption": (american.STABILITY, american.exclusions),
            **{
                name: (digital.STABILITY, g.exclusions)
                for name in digital.INSTRUMENTS.values()
            },
            "BarrierOption": (barrier.STABILITY, g.exclusions),
            "BinaryBarrierOption": (binary.STABILITY, binary.exclusions),
            "TouchOption": (binary.STABILITY, binary.exclusions),
            **{
                name: (asian.STABILITY, asian.exclusions)
                for name in asian.INSTRUMENTS.values()
            },
        }
        g.require(fields[1] in contracts, "unknown generated instrument")
        limits, exclusions = contracts[fields[1]]
        unavailable = exclusions(inputs)
        g.require(
            set(outputs) == set(g.MEASURES) - unavailable.keys(),
            "incomplete measures",
        )
        g.require(
            {
                key.removeprefix("unavailable_")
                for key in inputs
                if key.startswith("unavailable_")
            }
            == unavailable.keys(),
            "invalid unavailable declarations",
        )
        for name in g.MEASURES:
            g.require(
                inputs.get(f"unit_{name}") == g.UNITS[name], f"invalid {name} unit"
            )
            if name in unavailable:
                g.require(
                    inputs[f"unavailable_{name}"] == unavailable[name],
                    "invalid unavailable reason",
                )
                continue
            uncertainty = float(inputs[f"uncertainty_{name}"])
            g.require(
                math.isfinite(uncertainty) and 0 <= uncertainty <= limits[name],
                "unstable output",
            )
            g.require(
                float(inputs[f"stability_limit_{name}"]) == limits[name],
                "invalid stability limit",
            )
            budget = float(inputs[f"numerical_tolerance_{name}"])
            g.require(
                math.isfinite(budget) and budget >= 0, "invalid numerical tolerance"
            )


def load_scenarios(path):
    config = json.loads(path.read_text(encoding="utf-8"))
    g.require(
        set(config) == {"defaults", "scenarios"}, "invalid scenario configuration"
    )
    defaults = config["defaults"]
    g.require(
        set(defaults) == {"inputs", "tolerances", "numerical_tolerances"},
        "invalid scenario defaults",
    )
    g.require(
        isinstance(config["scenarios"], list) and config["scenarios"], "no scenarios"
    )
    scenarios = []
    for scenario in config["scenarios"]:
        g.require(
            {"case_id", "inputs"} <= set(scenario) <= {"case_id", *defaults},
            "invalid scenario overrides",
        )
        expanded = dict(scenario)
        for field in defaults:
            expanded[field] = dict(defaults[field], **scenario.get(field, {}))
        validate_scenario(expanded)
        scenarios.append(expanded)
    g.require(
        len({item["case_id"] for item in scenarios}) == len(scenarios),
        "duplicate scenario identifier",
    )
    return scenarios


def regenerate(
    fixture=FIXTURE,
    scenarios_path=g.PROJECT / "scenarios.json",
    profiles_path=g.PROJECT / "numerical_engines.json",
):
    g.require(
        version("QuantLib") == g.ql.__version__ == "1.43",
        "run with the frozen uv environment",
    )
    scenarios = load_scenarios(scenarios_path)
    profiles = numerical_profiles(profiles_path)
    generated = []
    for item in scenarios:
        reference = g.reference(item["inputs"])
        generated.append(
            g.serialize_row(
                g.reference_row(
                    item["case_id"],
                    item["inputs"],
                    reference,
                    item["tolerances"],
                    item["numerical_tolerances"],
                )
            )
        )
        if not g.exclusions(item["inputs"]):
            generated.extend(
                numerical_row(item, profile, reference) for profile in profiles
            )
    generated += list(american.rows())
    generated += list(digital.rows())
    generated += list(barrier.rows())
    generated += list(binary.rows())
    generated += list(asian.rows())
    generated.sort(key=lambda row: row.split("\t")[0])
    content = (
        "\n".join(
            [
                "# Language-neutral reference manifest. Generated by tools/quantlib-oracle/generate.py using QuantLib.",
                "# inputs/outputs/tolerances use key=value;",
                '# Monte Carlo uses seed|paths|steps|tolerance. A dash means "not applicable".',
                "\t".join(g.HEADER),
                *generated,
            ]
        )
        + "\n"
    )
    validate_manifest(content)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=fixture.parent, delete=False) as output:
            temporary = Path(output.name)
            output.write(content.encode("utf-8"))
        os.replace(temporary, fixture)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    print(f"Generated {len(generated)} QuantLib price and Greek references")


if __name__ == "__main__":
    regenerate()
